run:
  tests: false

linters:
  enable:
    - lll
    - bodyclose

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-dirs:
    - vendor/
    - uploads/

  exclude-files:
    - ".pb.go"
