version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    build:
<<<<<<< HEAD
      dockerfile: ./db/migrations/Dockerfile
=======
      dockerfile: cmd/app/postgres.dockerfile
>>>>>>> ed945f869dcea4edeadb645e222b10658ca51b2a
    ports:
      - 5432:5432
    networks:
      - app_network
    restart: always

  films:
    container_name: films
    build:
<<<<<<< HEAD
      dockerfile: ./cmd/films/Dockerfile
=======
      dockerfile: ./cmd/films/films.dockerfile
>>>>>>> ed945f869dcea4edeadb645e222b10658ca51b2a
    ports:
      - 8020:8020
    networks:
      - app_network
    depends_on:
      - postgres
    restart: always

  users:
    container_name: users
    build:
<<<<<<< HEAD
      dockerfile: ./cmd/users/Dockerfile
=======
      dockerfile: ./cmd/users/users.dockerfile
>>>>>>> ed945f869dcea4edeadb645e222b10658ca51b2a
    ports:
      - 8030:8030
    networks:
      - app_network
    depends_on:
      - postgres
    restart: always

  sessions:
    container_name: sessions
    environment:
      SECRETKEY: SECRETKEY
    build:
<<<<<<< HEAD
      dockerfile: ./cmd/sessions/Dockerfile
=======
      dockerfile: ./cmd/sessions/sessions.dockerfile
>>>>>>> ed945f869dcea4edeadb645e222b10658ca51b2a
    ports:
      - 8010:8010
    networks:
      - app_network
    depends_on:
      - postgres
    restart: always

  app:
    container_name: app
    build:
<<<<<<< HEAD
      dockerfile: ./cmd/app/Dockerfile
=======
      dockerfile: main.dockerfile
>>>>>>> ed945f869dcea4edeadb645e222b10658ca51b2a
    ports:
      - 8081:8081
    networks:
      - app_network
    depends_on:
      - films
      - users
      - sessions
      - postgres
    restart: always

networks:
  app_network:
    driver: bridge