scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']
    metrics_path: /metrics