scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']
    metrics_path: /metrics
  - job_name: films
    scrape_interval: 5s
    static_configs:
      - targets: ['films:8021']
    metrics_path: /metrics
  - job_name: auth
    scrape_interval: 5s
    static_configs:
      - targets: ['sessions:8011']
    metrics_path: /metrics
  - job_name: users
    scrape_interval: 5s
    static_configs:
      - targets: ['users:8031']
    metrics_path: /metrics