name: project-CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
 
      - name: build
        run: go build ./cmd/app/main.go

      - name: install lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: lint
        run: golangci-lint run

      - name: test
        run: go test -v ./...

  deploy:
    name: deploy netrunnerflix
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /home/ubuntu/back/test/2024_1_Netrunners && git pull
      - name: Build containers
        uses: appleboy/ssh-action@master
        with:
          timeout: 200m
          command_timeout: 200m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /home/ubuntu/back/test/2024_1_Netrunners && sudo docker-compose build
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /home/ubuntu/back/test/2024_1_Netrunners && sudo docker-compose down proxy app films sessions users && sudo docker compose up -d proxy app films sessions users